### ISSUE TITLE
NOT ABLE TO RUN

### ISSUE THREAD

**Issue by wtfaryan** [seadhy/Spotify-Account-Creator#21]
I am not able to use this can somebody provide me a tutorial on how to run this

**Comment by ImmaSB** [comment]
1) If you are on windows open command prompt, if on linux open terminal
2) If you have git installed, type `git clone https://github.com/seadhy/Spotify-Account-Creator`, otherwise [Download This Repo ZIP](https://github.com/seadhy/Spotify-Account-Creator/archive/refs/heads/main.zip) and extract it.
3) Type `cd Downloads/Spotify-Account-Creator` (Other the path to where you have extracted the file)
4) Edit the config.json file as to your needs
5) Run `python creator.py`

**Comment by seadhy** [comment]
https://streamable.com/v4ooti
