### ISSUE TITLE
 [Error Occurred] > Cannot access local variable 'proxy' where it is not associated with a value. Retrying...

### ISSUE THREAD

**Issue by eziolk192** [seadhy/Spotify-Account-Creator#23]
It say 
 **[Error Occurred] > Cannot access local variable 'proxy' where it is not associated with a value. Retrying...**

How can I fix this??? 
![image](https://user-images.githubusercontent.com/128672271/227114444-f00bf441-8ea8-4a04-a5cc-3c731822b082.png)

**Comment by enriluis** [comment]
this happend to me with use VPN...

**Comment by seadhy** [comment]
Add proxy to data/proxies.txt file

**Comment by xplutos** [comment]
[09:57:47] [Error Occurred] > Server disconnected without sending a response.. Retrying...

**Comment by ins72tt** [comment]
how do i add the proxy data

**Comment by ins72tt** [comment]
i have password and username and ip and port, how do i fill the file?

**Comment by seadhy** [comment]
> It say **[Error Occurred] > Cannot access local variable 'proxy' where it is not associated with a value. Retrying...**
> 
> How can I fix this??? ![image](https://user-images.githubusercontent.com/128672271/227114444-f00bf441-8ea8-4a04-a5cc-3c731822b082.png)

> this happend to me with use VPN...



The problem was that when using VPN, it entered this section and because the proxy was not used, it could not find the proxy variable and gave an error. I fixed this. If you're not using a proxy while using the program, you probably need to turn off the VPN or switch to a VPN service that Spotify doesn't detect.
![image](https://user-images.githubusercontent.com/82868382/232640575-68b2ee5b-79f4-4765-9e03-68fb2e606e6f.png)
